=== imiguelm25-hub/ERRONKA2-4.Taldea-/WEB/erronka2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="langileak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="langilea" type="tLangilea" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="tLangilea">
       <xs:sequence>
            <xs:element name="izena" type="xs:string"/>
            <xs:element name="abizena" type="xs:string"/>
            <xs:element name="emaila" type="xs:string"/>
            <xs:element name="telefonoa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{9}"/>
                    </xs:restriction>
                 </xs:simpleType>
            </xs:element>
            <xs:element name="data" type="xs:date"/>

            <xs:element name="nagusia" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="izena" type="xs:string"/>
                        <xs:element name="abizena" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="idNagusi" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[0-9]{8}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>

            <xs:choice >
                <xs:element name="bulegariDatuak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lanpostua">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="idLanpostu" type="xs:integer" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>   
                        </xs:sequence> 
                    </xs:complexType>
                </xs:element>

                <xs:element name="saltzaileDatuak">
                    <xs:complexType>
                        <xs:sequence>
                        <xs:element name="erabiltzailea" type="xs:string"/>
                        <xs:element name="pasahitza" type="xs:string"/>
                        </xs:sequence>  
                    </xs:complexType>
                </xs:element>
            </xs:choice>

        </xs:sequence>
        <xs:attribute name="mota" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="bulegaria"/>
                    <xs:enumeration value="saltzailea"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="idLangile" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{8}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== imiguelm25-hub/ERRONKA2-4.Taldea-/WEB/erronka2.xml
<?xml version="1.0" encoding="UTF-8"?>

<langileak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="erronka2.xsd">

    <!-- BULEGARIA -->
    <langilea mota="bulegaria" idLangile="12345678">
        <izena>Jon</izena>
        <abizena>Etxeberria</abizena>
        <emaila>jon.etxeberria@example.com</emaila>
        <telefonoa>600123456</telefonoa>
        <data>2024-03-15</data>

        <nagusia idNagusi="87654321">
            <izena>Ane</izena>
            <abizena>Perez</abizena>
        </nagusia>

        <bulegariDatuak>
            <lanpostua idLanpostu="1">Administratzailea</lanpostua>
        </bulegariDatuak>
    </langilea>


    <!-- SALTZAILEA -->
    <langilea mota="saltzailea" idLangile="23456789">
        <izena>Maite</izena>
        <abizena>Cuesta</abizena>
        <emaila>maite.cuesta@example.com</emaila>
        <telefonoa>611987654</telefonoa>
        <data>2023-09-01</data>

        <saltzaileDatuak>
            <erabiltzailea>mcuesta</erabiltzailea>
            <pasahitza>123</pasahitza>
        </saltzaileDatuak>
    </langilea>

</langileak>
